# Site settings
title: "Ted Aronson"
email: hi@tedaronson.com
description: "Rocket Surgeon / Programmer / Game Designer"
baseurl: ""
url: "https://tedw4rd.github.io"
title_description: "Hi! I'm Ted. I'm a certified* rocket surgeon, amongst many other things. <br/>I like to make games! You can see a few in my <a href="/portfolio">Portfolio</a><br/>Sometimes I make stuff out of wood and sell it! You can see that on my <a href="https://instagram.com/firewaterfabrication">Instagram</a><br/>Eventually I might start blogging at <a href="https://www.departmentofrocketsurgery.com">Department of Rocket Surgery</a>, but who knows?<br/>You can find more about me <a href="/about">here</a>"
title_image: "assets/img/photo.png"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: 
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: tedw4rd
github_username:  tedw4rd
instagram_username: firewaterfabrication
reddit_username: 
linkedin_link: https://www.linkedin.com/in/theodorearonson/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Theme by <a href=\"https://github.com/jacobtomlinson/carte-noire\">Jacob Tomlinson</a>"
footer_right: "Bwoop &nbsp;<i class=\"fa fa-heart\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
